export const metadata = {
  title: 'Education Next Site',
  description: 'Generated by Next.js',
}

import "./global.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fa" dir="rtl">
      <head>
        <link rel="stylesheet" href="/assets/css/font.css" />
      </head>
      <body>{children}</body>
    </html>
  )
}
