export const metadata = {
  title: 'Education Next Site',
  description: 'Generated by Next.js',
}

import "./global.css";

import SiteHeader from "@/components/layout/site/header";
import SiteFooter from "@/components/layout/site/footer";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fa" dir="rtl">
        <head>
            <link rel="stylesheet" href="/assets/css/font.css" />
        </head>
        <body>
            <SiteHeader />
            {children}
            <SiteFooter />
        </body>
    </html>
  )
}
