export const metadata = {
  title: 'site layout',
  description: 'Generated by Next.js',
}


import SiteHeader from "@/components/layout/site/header";
import SiteFooter from "@/components/layout/site/footer";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
        <SiteHeader />
        {children}
        <SiteFooter />
    </>
  )
}
